---
title: "PAM (Mark)"
author: "Tim Finney"
date: "`r Sys.Date()`"
output: html_document
---

| k | ASW | Clusters | Poorly classified |
|:------|:------|------------------------------------------------------------|------------|
| 2 | 0.243 | [UBS Aleph B D L W Theta 565 2427 it-a it-aur it-b it-c it-d it-f it-ff-2 it-i it-k it-l it-q it-r-1 (vg) syr-pal syr-s cop-sa cop-bo arm eth geo Augustine] [A C Delta Psi f-1 f-13 28 33 157 180 205 579 597 700 892 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] | Theta 2427 arm 565 it-aur L Augustine geo it-l it-q vg it-f syr-pal eth |
| 3 | 0.323 | [UBS Aleph B C L W Delta (Psi) 892 2427 it-k syr-s cop-sa cop-bo] [A f-1 f-13 28 33 157 180 205 579 597 700 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect it-aur it-f it-l syr-p syr-h syr-pal eth geo slav Augustine] [D Theta 565 it-a it-b it-c it-d it-ff-2 (it-i) it-q it-r-1 vg arm] | C syr-s arm vg |
| 4 | 0.305 | [UBS Aleph B C L W Delta (Psi) 892 2427 it-k cop-sa cop-bo] [A f-1 f-13 28 33 157 180 205 579 597 700 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [D Theta it-a it-b it-d it-ff-2 (it-i) it-r-1] [565 it-aur it-c it-f it-l it-q (vg) syr-pal syr-s arm eth geo Augustine] | syr-pal C W it-q Theta it-c eth |
| 5 | 0.313 | [UBS Aleph (B) L Delta Psi 2427 cop-sa cop-bo] [A C f-13 33 157 180 579 597 700 892 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [D it-a it-b it-c it-d (it-ff-2) it-i it-k it-r-1] [W (f-1) 28 205 565 syr-s arm geo] [Theta it-aur it-f it-l it-q (vg) syr-pal eth Augustine] | eth 892 |
| 6 | 0.314 | [UBS Aleph (B) L Delta Psi 2427 cop-sa cop-bo] [A C f-13 33 157 180 579 597 700 892 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [D it-a it-b it-c it-d (it-ff-2) it-i it-k it-r-1] [W 565 syr-s (arm) geo] [Theta it-aur it-f it-l it-q (vg) syr-pal eth Augustine] [f-1 28 (205)] | Theta f-13 geo eth 565 892 |
| 7 | 0.285 | [UBS Aleph (B) L Psi 2427] [A C f-13 33 157 180 579 597 700 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [D it-a it-b it-c it-d (it-ff-2) it-i it-k it-r-1] [W 565 syr-s (arm) geo] [Delta 892 cop-sa (cop-bo)] [Theta it-aur it-f it-l it-q (vg) syr-pal eth Augustine] [f-1 28 (205)] | Theta f-13 it-k geo C 892 eth 565 Delta |
| 8 | 0.291 | [UBS Aleph (B) L Psi 2427] [A C f-13 33 157 180 579 597 700 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [D Theta it-a it-b it-d it-ff-2 (it-i) it-r-1] [W 565 syr-s (arm) geo] [Delta 892 cop-sa (cop-bo)] [f-1 28 (205)] [it-aur it-c it-f it-l it-q (vg) syr-pal eth Augustine] [(it-k)] | it-c f-13 syr-pal geo C Theta 892 565 Delta eth |
| 9 | 0.302 | [UBS Aleph (B) L Psi 2427] [A C f-13 33 157 180 579 597 700 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [D it-a it-b it-c it-d (it-ff-2) it-i it-r-1] [W syr-s (arm) geo] [Delta 892 cop-sa (cop-bo)] [(Theta) 565 syr-pal] [f-1 28 (205)] [it-aur it-f it-l it-q (vg) eth Augustine] [(it-k)] | f-13 geo eth C 892 Delta |
| 10 | 0.305 | [UBS Aleph (B) L Psi 2427] [A C f-13 33 157 180 579 597 700 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [D it-a it-b it-c it-d (it-ff-2) it-i it-r-1] [(W)] [Delta 892 cop-sa (cop-bo)] [(Theta) 565 syr-pal] [f-1 28 (205)] [it-aur it-f it-l it-q (vg) eth Augustine] [(it-k)] [syr-s (arm) geo] | f-13 eth C 892 Delta |
| 11 | 0.318 | [UBS Aleph (B) Psi 2427] [A f-13 33 157 180 579 597 700 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [C L (Delta)] [D it-a it-b it-c it-d (it-ff-2) it-i it-r-1] [(W)] [(Theta) 565 syr-pal] [f-1 28 (205)] [892 cop-sa (cop-bo)] [it-aur it-f it-l it-q (vg) eth Augustine] [(it-k)] [syr-s (arm) geo] | eth 892 L |
| 12 | 0.300 | [UBS Aleph (B) Psi 2427] [A f-13 33 157 180 579 597 700 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [C L (Delta)] [D it-a (it-d)] [(W)] [(Theta) 565 syr-pal] [f-1 28 (205)] [892 cop-sa (cop-bo)] [it-aur it-c it-f it-l it-q (vg) eth Augustine] [it-b it-ff-2 (it-i) it-r-1] [(it-k)] [syr-s (arm) geo] | 892 eth it-c L |
| 13 | 0.300 | [UBS Aleph (B) Psi 2427] [A f-13 33 157 180 579 597 700 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [C L (Delta)] [D it-a (it-d)] [(W)] [(Theta) 565 syr-pal] [f-1 28 (205)] [892 cop-sa (cop-bo)] [it-aur it-c it-f it-l it-q (vg) eth Augustine] [it-b it-ff-2 (it-i) it-r-1] [(it-k)] [(syr-s)] [(arm) geo] | 892 eth it-c L |
| 14 | 0.297 | [UBS Aleph (B) Psi 2427] [A f-13 33 157 180 579 597 700 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [C L (Delta)] [D it-a (it-d)] [(W)] [(Theta) 565] [f-1 28 (205)] [892 cop-sa (cop-bo)] [it-aur it-c it-f it-l it-q (vg) eth Augustine] [it-b it-ff-2 (it-i) it-r-1] [(it-k)] [(syr-pal)] [(syr-s)] [(arm) geo] | 892 eth it-c L |
| 15 | 0.294 | [UBS Aleph (B) Psi 2427] [A f-13 33 157 180 579 597 700 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [C L (Delta)] [D it-a (it-d)] [(W)] [(Theta) 565] [f-1 28 (205)] [892 cop-sa (cop-bo)] [it-aur it-f it-l it-q (vg) eth Augustine] [it-b it-ff-2 (it-i) it-r-1] [(it-c)] [(it-k)] [(syr-pal)] [(syr-s)] [(arm) geo] | eth 892 L |
| 16 | 0.291 | [UBS Aleph (B) Psi 2427] [A f-13 33 157 180 597 700 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [C L (Delta)] [D it-a (it-d)] [(W)] [(Theta) 565] [f-1 28 (205)] [(579)] [892 cop-sa (cop-bo)] [it-aur it-f it-l it-q (vg) eth Augustine] [it-b it-ff-2 (it-i) it-r-1] [(it-c)] [(it-k)] [(syr-pal)] [(syr-s)] [(arm) geo] | eth 892 L |
| 17 | 0.300 | [UBS Aleph (B) 2427] [A f-13 33 157 180 597 700 1006 1010 1071 1241 1243 1292 1342 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [C (Delta)] [D it-a (it-d)] [L (Psi) 892] [(W)] [(Theta) 565] [f-1 28 (205)] [(579)] [it-aur it-f it-l it-q (vg) eth Augustine] [it-b it-ff-2 (it-i) it-r-1] [(it-c)] [(it-k)] [(syr-pal)] [(syr-s)] [cop-sa (cop-bo)] [(arm) geo] | eth |
| 18 | 0.304 | [UBS Aleph (B) 2427] [A f-13 33 157 180 597 700 1006 1010 1071 1241 1243 1292 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [C (Delta)] [D it-a (it-d)] [L (Psi) 892] [(W)] [(Theta) 565] [f-1 28 (205)] [(579)] [(1342)] [it-aur it-f it-l it-q (vg) eth Augustine] [it-b it-ff-2 (it-i) it-r-1] [(it-c)] [(it-k)] [(syr-pal)] [(syr-s)] [cop-sa (cop-bo)] [(arm) geo] | eth |
| 19 | 0.302 | [UBS Aleph (B) 2427] [A f-13 33 157 180 597 700 1006 1010 1071 1241 1243 1292 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [(C)] [D it-a (it-d)] [L (Psi) 892] [(W)] [(Delta)] [(Theta) 565] [f-1 28 (205)] [(579)] [(1342)] [it-aur it-f it-l it-q (vg) eth Augustine] [it-b it-ff-2 (it-i) it-r-1] [(it-c)] [(it-k)] [(syr-pal)] [(syr-s)] [cop-sa (cop-bo)] [(arm) geo] | eth |
| 20 | 0.306 | [UBS Aleph (B) 2427] [A f-13 33 157 180 597 700 1006 1010 1071 1241 1243 1292 1424 1505 (Byz) E F G H N Sigma Lect syr-p syr-h slav] [(C)] [D it-a (it-d)] [L (Psi) 892] [(W)] [(Delta)] [(Theta) 565] [f-1 28 (205)] [(579)] [(1342)] [it-aur it-f it-l it-q (vg) Augustine] [it-b it-ff-2 (it-i) it-r-1] [(it-c)] [(it-k)] [(syr-pal)] [(syr-s)] [cop-sa (cop-bo)] [(arm) geo] [(eth)] |  |
